### ISSUE TITLE
很希望现在国内技术比较强的公司能够多使用中文

### ISSUE THREAD

**Issue by yemadu** [Huawei/containerops#483]
很希望现在国内技术比较强的公司能够多使用中文. 
发扬光大中国, 带动国内技术的发展也是一件好事!!!

人家外国人, 都开始很多文档支持中文了, 但是国人就是不用中文. 

华为, 要为中华有为!

**Comment by zzhaoy** [comment]
楼上的同学，要不你开源个中文编程语言项目，我们去贡献~

**Comment by yemadu** [comment]
注释能用中文就 极好的

**Comment by nobodxbodon** [comment]
几乎所有的主流编程语言都支持中文命名类/方法/变量. 不过个人猜度, 也许是因为这里主要面向国外程序员所以这里开源的项目还是用英文代码?
