### ISSUE TITLE
A suggestion for the dirctory (“containerops/component/images/” )

### ISSUE THREAD

**Issue by haijunTan** [Huawei/containerops#499]
containerops/component/images/
-------------------------------------- golang/
----------------------------------------------runtime_base/
----------------------------------------------golint_tool/
----------------------------------------------gofmt_tool/
----------------------------------------------XX_tool/
--------------------------------------javalang/
--------------------------------------XXlang/

**Comment by genedna** [comment]
@haijunTan,

The image is the base image, and it's not a DevOps component. If you would write component, you choose an image from the images.

Like some components in the `cncf/demo`.

```Dockerfile
FROM docker.io/containerops/golang:1.8.3
```

Tips:
Using **[Markdown](https://guides.github.com/features/mastering-markdown)** lets your issue more readable than plain text.

**Comment by haijunTan** [comment]
**INFO[0035] Get https://index.docker.io/v1/repositories/containerops/golang/images: dial tcp: lookup index.docker.io: no such host**
