### ISSUE TITLE
issue: i think  “”$GOPATH:/bin“” is “”$GOPATH/bin“”

### ISSUE THREAD

**Issue by haijunTan** [Huawei/containerops#508]
In this file：https://github.com/Huawei/containerops/blob/master/demo/cncf/kubernetes/Dockerfile
Line 31 ：ENV PATH $PATH:$GOROOT/bin:$GOPATH**:**/bin:$GOPATH/src/github.com/Huawei/containerops

I think it is：
 ENV PATH $PATH:$GOROOT/bin:$GOPATH**/**bin:$GOPATH/src/github.com/Huawei/containerops

**Comment by genedna** [comment]
There is a `bin` folder in **Go** home path include `go`, `godoc` and others. And some packages install binary execute files in the `bin` folder. So the `$GOPATH/bin` should in the `PATH` environment. 

This is a `Go` path example,

```bash
export GOPATH=$HOME/gopath
export GOROOT=$HOME/go
export GOBIN=$GOROOT/bin
export GOTOOTLS=$GOROOT/pkg/tool
export PATH=$PATH:$GOBIN:$GOTOOTLS:$GOPATH/bin:$HOME/.cargo/bin
```
